name: Cypress Schduled Tests

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2] # Uses 2 parallel instances

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name:  Cypress scheduled run
        uses: cypress-io/github-action@v6
        with:
          # Records to Cypress Cloud 
          record: true
          parallel: true # Runs test in parallel using settings above
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
