name: Cypress Tests

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Install Cypress
        run: npx cypress install

      - name: Verify Cypress Installation
        run: npx cypress verify

      - name: Run Cypress tests
        run: npx cypress run --record --key ${{ secrets.CYPRESS_RECORD_KEY }}
